// <auto-generated />
namespace JTTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_notification_method : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_notification_method));
        
        string IMigrationMetadata.Id
        {
            get { return "201706221546252_add_notification_method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
